//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieMatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieMood
    {
        public string title { get; set; }
        public Nullable<int> runtime { get; set; }
        public string mood { get; set; }
        public string overview { get; set; }
        public string poster_path { get; set; }
        public string imdb_id { get; set; }
    }
}
