//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieMatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieMood
    {
        public string MovieTittle { get; set; }
        public string RunTime { get; set; }
        public string Mood { get; set; }
        public string Description { get; set; }
        public string Poster { get; set; }
    }
}
